# Generated by Django 4.1.7 on 2023-04-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(max_length=40)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.county')),
            ],
        ),
    ]
