# Generated by Django 4.1.7 on 2023-03-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_rename_type_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
