# Generated by Django 4.1.7 on 2023-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_remove_shipping_constituency_delete_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
